### PR TITLE
audit #2 improvements

### PR DESCRIPTION
**Pull request by 10xSebastian**
[H01 - Native Token may get stuck in contract](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#H01)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/76168633c16ead3ec1e6952df8f131395cf8294c

[M01 - Excess eth not refunded](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#M01)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/03341a46d6548fe5c5ceb9c5e3e219b0a5c01c75

[L01 - Ownable contract has a single step ownership transferred](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#L01)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/00038cf7d4194e8f04af47985a9af7d78b219e5e

[L02 - Pay function may revert without proper error message returned](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#L02)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/3f83a6bd2e786fbfa52c1089a3a37c043311b02a

[L03 - Missing zero address check](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#L03)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/d77483047d6c66d55b7b927f6c0301c2bbf9c93a

[I01 - Using bools for storage incurs overhead.](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#I01)
fixed with: 
1. https://github.com/DePayFi/depay-evm-router/pull/61/commits/bb3a95a419b702539de7bf07e64a4bb1464a2141
2. https://github.com/DePayFi/depay-evm-router/pull/61/commits/c309e2d01977866bbbe16db0983d8db89580481f

[I02 - Long revert strings.](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#I02)
fixed with: 
1. https://github.com/DePayFi/depay-evm-router/pull/61/commits/5151b8fb8fe3eb94e673704f3b454672cbf45b62
2. https://github.com/DePayFi/depay-evm-router/pull/61/commits/db4f48bd54c23fa1d1838a742414d0c22ee9e918

[I03 - No Proper Natspec Comments](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#I05)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/4e9b421c3e5f4af0b0900a8a1def2784558941c3

[I04 - Issue: Floating Solidity Version](https://github.com/DePayFi/depay-evm-router/blob/master/audits/v2/Audit2.md#I06)
fixed with: https://github.com/DePayFi/depay-evm-router/pull/61/commits/640788dfd6fe8703453cae024900e527269bd416

### CODE REVIEW

**Comment by Timidan** [comment]
All issues have been fixed, but this leaves around a high vulnerability of allowing any external party to withdraw any ether in the Forwarder contract, this can be easily solved by just introducing a precondition hook to `forwarder.forward()`

**Comment by 10xSebastian** [comment]
mitigated potential eth extraction from forwarded in https://github.com/DePayFi/depay-evm-router/pull/61/commits/b2b223b7edf6b7a1dc0b0ac641fe321dff7af1d6

Also added emergency withdrawal, because if stuck eth is possible and we prevent others from extracting it, we need to have some way to recover it.

**Comment by 10xSebastian** [comment]
mitigated external eth extraction for potentially stuck eth. also added emergency withdrawal, because if we are afraid of others extraction accidentally stuck eth, we need to have some way to recover it from the forwarder.

**Comment by Timidan** [comment]
looks good to me!

**Pull request merged**
